language: node_js
node_js:
  - 'node'
cache:
  yarn: true
before_script:
  - yarn global add typescript
  - lerna bootstrap --force-local
script:
  - yarn run test
after_success:
  - yarn run test:coverage
